all: homework05
	g++ -L. homework05.o -o homework05
	
SRC_FILES = $(wildcard dir/*.cpp)

homework05: 21500868_homework05.cpp
	g++ -std=c++11 -c 21500868_homework05.cpp -o homework05.o
	
clean:
	rm *.o
	rm homework05